apiVersion: 1
datasources:
  - name: Postgresql
    type: postgres
    url: postgres:5432
    database: postgres
    user: grafanareader
    secureJsonData:
      password: 'password'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0 
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
